import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "@/components/themes/ThemeProvider";
import Navbar from "@/components/layout/Navbar";
// import { NavContextProvider } from "@/context/NavContext";
import Footer from "@/components/layout/Footer";
import { Providers } from "./_providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={{ colorScheme: "light" }}
      className="light"
      suppressHydrationWarning
    >
      <body
        className={`${poppins.className} bg-light-30 dark:bg-dark-100 text-black dark:text-white`}
      >
        {/* <ThemeProvider attribute="class" enableSystem={true}>
          <NavContextProvider> */}
        <Providers>
          <Navbar />
          <main className="relative overflow-x-hidden py-[100px] w-appWidth mx-auto">
            {children}
          </main>
          <Footer />
        </Providers>
        {/* </NavContextProvider>
        </ThemeProvider> */}
      </body>
    </html>
  );
}
